# Generated by Django 4.2.21 on 2025-05-27 17:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tracker', '0010_alter_userprofile_current_streak_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='detox_streak',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
