# Generated by Django 4.2.21 on 2025-05-27 17:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tracker', '0011_userprofile_detox_streak'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='detoxsession',
            options={'ordering': ['-start_time']},
        ),
        migrations.AddField(
            model_name='detoxsession',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name='detoxsession',
            name='duration',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='detoxsession',
            name='start_time',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
