# Generated by Django 4.2.21 on 2025-06-09 09:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tracker', '0012_alter_detoxsession_options_detoxsession_is_active_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='last_checkin_date',
            field=models.DateField(blank=True, null=True),
        ),
    ]
