# Generated by Django 4.2.21 on 2025-06-09 09:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tracker', '0013_userprofile_last_checkin_date'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userprofile',
            name='last_checkin',
        ),
    ]
